export const AUTH_START = "auth_start"
export const AUTH_FAIL = "auth_fail"
export const AUTH_SUCCESS = "auth_success"
export const REG_SUCCESS = "reg_success"
export const AUTH_LOGOUT = "auth_logout"
export const SHOW_LOGIN = "show_login"